### ISSUE TITLE
Show Design

### ISSUE THREAD

**Issue by ijunaid8989** [ggoodfellass/fyp_design#1]
Post Images of design each page what you have made so far!

**Comment by shakeelrauf** [comment]
![screenshot from 2016-11-20 21 34 08](https://cloud.githubusercontent.com/assets/20041427/20464443/8b8e9590-af69-11e6-87f9-5a49bb95a286.png)
![Uploading Screenshot from 2016-11-20 21:34:14.png…]()
![Uploading Screenshot from 2016-11-20 21:34:34.png…]()
![Uploading Screenshot from 2016-11-20 21:34:48.png…]()

**Comment by shakeelrauf** [comment]
![screenshot from 2016-11-20 21 34 14](https://cloud.githubusercontent.com/assets/20041427/20464467/bbf6f7cc-af69-11e6-8eed-9ba30279e7eb.png)

**Comment by shakeelrauf** [comment]
![screenshot from 2016-11-20 21 34 34](https://cloud.githubusercontent.com/assets/20041427/20464473/d9cc0120-af69-11e6-8ca5-8ac7c58d7424.png)

**Comment by shakeelrauf** [comment]
![screenshot from 2016-11-20 21 34 48](https://cloud.githubusercontent.com/assets/20041427/20464478/ea6a9226-af69-11e6-97dd-715862c31037.png)

**Comment by shakeelrauf** [comment]
![screenshot from 2016-11-20 21 41 15](https://cloud.githubusercontent.com/assets/20041427/20464492/186c0592-af6a-11e6-97b8-68615ada3857.png)
